### ISSUE TITLE
Switch license to MIT

### ISSUE THREAD

**Issue by ncoghlan** [reynoldsnlp/pip_inside#4]
`pip` is licensed under MIT, so it isn't able to accept GPL'ed contributions: https://github.com/pypa/pip/blob/master/LICENSE.txt

Given that the hope is that the REPL level install functionality in this project will eventually be rolled back into `pip` itself, it's probably better to use MIT as the license here as well.

(@reynoldsnlp I'm not sure how familiar you are with the vagaries of software licensing, but relicensing now is simple, as you're the only code contributor. If/when other folks contribute, you'd need their permission to change it, but right now, it's solely your decision)

**Comment by reynoldsnlp** [comment]
I actually just woke up wondering if I should have checked `pip`'s license to make sure this is compatible. Glad you noticed.
